<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageVersion>1.2.0</PackageVersion>
    <PackageTags>Serilog Sink EntityFrameworkCore</PackageTags>
    <Description>Entity model for Serilog sink based on EntityFrameworkCore.</Description>
    <PackageReleaseNotes>Update to .NET 10.0 .</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

</Project>
